### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by tombentley**
Untested, but some initial work on configuring logging of Kafka and Zookeeper to:

* only log to the console, not to files, and
* use a consistent date format at least.

See #21.

### CODE REVIEW

**Comment by scholzj** [comment]
@tombentley 
* In Kafka pods, there still seems to be some GC log: `/var/lib/kafka/logs0/kafkaServer-gc.log.0.current `. Can we move that as well?
* If we can do the above, can we remove the configuration for the `LOG_DIR` from `kafka_run.sh`?
* Can we remove the `LOG_DIR` from `kafka_connect_run.sh`?

**Comment by scholzj** [comment]
@tombentley 
* In Kafka pods, there still seems to be some GC log: `/var/lib/kafka/logs0/kafkaServer-gc.log.0.current `. Can we move that as well?
* If we can do the above, can we remove the configuration for the `LOG_DIR` from `kafka_run.sh`?
* Can we remove the `LOG_DIR` from `kafka_connect_run.sh`?

**Comment by scholzj** [comment]
Is there really no API to change the log levels on the fly? I didn't realized that before, but that sounds like quite a big missing feature in Kafka. 

I think that having it configurable through env. variables makes sense but I can also imagine that we split it into two separate PRs.

**Comment by tombentley** [comment]
The thought of having the GC logs in with the kafka logs all via stdout makes me feel a little dirty, but I agree we can't really leave a log file growing in the container. Let me look at it.

AFAIK log4j doesn't directly support config via env vars. We would have to use System properties, and set via `java -D` from the env vars. I can do this too, but I'll do that in a separate PR. 

As for reconfiguring on-the-fly, I would wait for https://github.com/apache/kafka/pull/3477 to be merged, which will get rid of log4j entirely.

**Comment by tombentley** [comment]
@scholzj I've done the fixes around gc logging, if you want to take another look.

**Comment by scholzj** [comment]
@tombentley LGTM. Thanks.

**Pull request merged**
